"""initial migration

Revision ID: a7462dadc452
Revises: 
Create Date: 2025-05-12 22:02:26.535908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7462dadc452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Emprunteur',
    sa.Column('Mat', sa.String(length=20), nullable=False),
    sa.Column('Nom', sa.String(length=100), nullable=True),
    sa.Column('Prenom', sa.String(length=100), nullable=True),
    sa.Column('CodeFil', sa.String(length=100), nullable=True),
    sa.Column('Niveau', sa.String(length=10), nullable=True),
    sa.Column('Groupe', sa.String(length=10), nullable=True),
    sa.Column('Anincription', sa.Date(), nullable=True),
    sa.Column('TypeEmploye', sa.String(length=20), nullable=True),
    sa.Column('Motdepasse', sa.String(length=100), nullable=True),
    sa.Column('Tel', sa.String(length=20), nullable=True),
    sa.Column('N_Pretes', sa.Integer(), nullable=True),
    sa.Column('CoteExo', sa.String(length=50), nullable=True),
    sa.Column('Numero', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Mat')
    )
    op.create_table('Inventaire_Ouvrage',
    sa.Column('Cote', sa.String(length=50), nullable=False),
    sa.Column('Titre_Ouvrage', sa.String(length=255), nullable=True),
    sa.Column('Auteur', sa.String(length=255), nullable=True),
    sa.Column('Editeur', sa.String(length=255), nullable=True),
    sa.Column('Langue', sa.String(length=100), nullable=True),
    sa.Column('Categorie', sa.String(length=100), nullable=True),
    sa.Column('Edition_Date', sa.Date(), nullable=True),
    sa.Column('Quantite', sa.Integer(), nullable=True),
    sa.Column('Support_Accom', sa.String(length=255), nullable=True),
    sa.Column('Observations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Cote')
    )
    op.create_table('Notification',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Mat', sa.String(length=20), nullable=True),
    sa.Column('CoteExo', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Message', sa.String(length=255), nullable=True),
    sa.Column('Vu', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Besoin_Livre',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Mat', sa.String(length=20), nullable=True),
    sa.Column('Titre_Ouvrage', sa.String(length=255), nullable=True),
    sa.Column('Auteur', sa.String(length=255), nullable=True),
    sa.Column('DateDemande', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Mat'], ['Emprunteur.Mat'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Exemplaires',
    sa.Column('CoteExo', sa.String(length=50), nullable=False),
    sa.Column('Cote', sa.String(length=50), nullable=True),
    sa.Column('Inv_Cote', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Cote'], ['Inventaire_Ouvrage.Cote'], ),
    sa.PrimaryKeyConstraint('CoteExo')
    )
    op.create_table('Reservation_Ouvrage',
    sa.Column('Mat', sa.String(length=20), nullable=False),
    sa.Column('CoteExo', sa.String(length=50), nullable=False),
    sa.Column('DateReserv', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['CoteExo'], ['Exemplaires.CoteExo'], ),
    sa.ForeignKeyConstraint(['Mat'], ['Emprunteur.Mat'], ),
    sa.PrimaryKeyConstraint('Mat', 'CoteExo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservation_Ouvrage')
    op.drop_table('Exemplaires')
    op.drop_table('Besoin_Livre')
    op.drop_table('Notification')
    op.drop_table('Inventaire_Ouvrage')
    op.drop_table('Emprunteur')
    # ### end Alembic commands ###
